---

# Network Security

- name: "2.3.11.1 (L1) Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "UseMachineId"
    data: "1"
    type: dword

- name: "2.3.11.2 (L1) Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: "allownullsessionfallback"
    data: "0"
    type: dword

- name: "2.3.11.3 (L1) Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
    name: "AllowOnlineID"
    data: "0"
    type: dword

- name: "2.3.11.4 (L1) Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters
    name: "SupportedEncryptionTypes"
    data: "2147483640"
    type: dword
  when: "'2.3.11.4' not in rules_list"

- name: "2.3.11.5 (L1) Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "NoLMHash"
    data: "1"
    type: dword

- name: "2.3.11.7 (L1) Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "LmCompatibilityLevel"
    data: "5"
    type: dword

- name: "2.3.11.8 (L1) Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP
    name: "LDAPClientIntegrity"
    data: "1"
    type: dword

- name: "2.3.11.9 (L1) Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NTLMMinClientSec"
    data: "537395200"
    type: dword

- name: "2.3.11.10 (L1) Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NTLMMinServerSec"
    data: "537395200"
    type: dword
  when: "'2.3.11.10' not in rules_list"
