---

# 2.3.1 Accounts 

- name: "2.3.1.1 (L1) Ensure 'Accounts: Administrator account status' is set to 'Disabled' (MS only)"
  win_security_policy:
    section: System Access
    key: EnableAdminAccount
    value: 0
  when: "'2.3.1.1' not in rules_list"

- name: "2.3.1.2 (L1) Ensure Accounts: Block Microsoft accounts is set to Users can't add or log on with Microsoft accounts"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "NoConnectedUser"
    data: "3"
    type: dword

- name: "2.3.1.3 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only)"
  win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: 0

- name: "2.3.1.4 (L1) Ensure Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "LimitBlankPasswordUse"
    data: "1"
    type: dword

- name: "2.3.1.5 (L1) Configure 'Accounts: Rename administrator account'"
  win_security_policy:
    section: System Access
    key: NewAdministratorName
    value: jon.anderson
  when: "'2.3.1.5' not in rules_list"

- name: "2.3.1.6 (L1) Configure 'Accounts: Rename guest account'"
  win_security_policy:
    section: System Access
    key: NewGuestName
    value: citrix
