---

# 19.1.3 Personalization (formerly Desktop Themes)

- name: "19.1.3.1 (L1) Ensure 'Enable screen saver' is set to 'Enabled'"
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
    name: "ScreenSaveActive"
    data: "1"
    type: string

- name: "19.1.3.2 (L1) Ensure 'Force specific screen saver: Screen saver executable name' is set to 'Enabled: scrnsave.scr'"
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
    name: "SCRNSAVE.EXE"
    data: "scrnsave.scr"
    type: string

- name: "19.1.3.3 (L1) Ensure 'Password protect the screen saver' is set to 'Enabled'"
  win_regedit:
    path: HKCU:\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
    name: "ScreenSaverIsSecure"
    data: "1"
    type: string

- name: "19.1.3.4 (L1) Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
  win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
    name: "ScreenSaveTimeOut"
    data: "900"
    type: string

