---

# 18.1.1 Personalization 

- name: "18.1.1.1 (L1) Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    name: "NoLockScreenCamera"
    data: "1"
    type: dword

- name: "18.1.1.2 (L1) Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    name: "NoLockScreenSlideshow"
    data: "1"
    type: dword

# 18.1.2 Handwriting Personalization

- name: "18.1.2.2 (L1) Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization
    name: "AllowInputPersonalization"
    data: "0"
    type: dword
