---

# Interactive Logon
#
- name: "2.3.7.1 (L1) Ensure 'Interactive logon: Do not require CTRL+ALT+DEL' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "DisableCAD"
    data: "0"
    type: dword

- name: "2.3.7.2 (L1) Ensure 'Interactive logon: Don't display last signed-in' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "DontDisplayLastUserName"
    data: "1"
    type: dword

- name: "2.3.7.3 (L1) Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "InactivityTimeoutSecs"
    data: "900"
    type: dword

- name: "2.3.7.4 (L1) Configure 'Interactive logon: Message text for users attempting to log on'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "LegalNoticeText"
    data: "***************************************************************************************************
    W A R N I N G! AUTHORIZED USE ONLY
    ***************************************************************************************************
    This computer system belongs to CITRIX SYSTEMS, INC. It is for authorized use only.
    Users have no explicit or implicit expectation of privacy.
    Unauthorized or improper use of this system may result in administrative disciplinary
    action, civil and criminal penalties. By continuing to use this system, you indicate
    your awareness of and consent to these terms and conditions of use. Do not continue
    to use this system if you do not agree to the conditions stated in this warning.
    ***************************************************************************************************"
    type: string

- name: "2.3.7.5 (L1) Configure 'Interactive logon: Message title for users attempting to log on'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: "LegalNoticeCaption"
    data: "Logon notice:"
    type: string

- name: "2.3.7.7 (L1) Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "PasswordExpiryWarning"
    data: "14"
    type: dword

- name: "2.3.7.8 (L1) Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "ForceUnlockLogon"
    data: "1"
    type: dword

- name: "2.3.7.9 (L1) Ensure 'Interactive logon: Smart card removal behavior' is set to 'Lock Workstation' or higher"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: "ScRemoveOption"
    data: "1"
    type: string

