---

# 2.2

- name: "2.2.1 (L1) Ensure 'Access Credential Manager as a trusted caller' is set to 'No One'"
  win_user_right:
    name: SeTrustedCredManAccessPrivilege
    users:
    action: set

- name: "2.2.3 (L1) Ensure 'Access this computer from the network' is set to 'Administrators, Authenticated Users' (MS only)"
  win_user_right:
    name: SeNetworkLogonRight
    users:
    - Administrators
    - Authenticated Users
    action: set

- name: "2.2.4 (L1) Ensure 'Act as part of the operating system' is set to 'No One'"
  win_user_right:
    name: SeTcbPrivilege
    users:
    action: set

- name: "2.2.6 (L1) Ensure 'Adjust memory quotas for a process' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeIncreaseQuotaPrivilege
    users:
    - Administrators
    - LOCAL SERVICE
    - NETWORK SERVICE
    action: set

- name: "2.2.7 (L1) Ensure 'Allow log on locally' is set to 'Administrators'"
  win_user_right:
    name: SeInteractiveLogonRight
    users:
    - Administrators
    action: set


- name: "2.2.9 (L1) Ensure 'Allow log on through Remote Desktop Services' is set to 'Administrators, Remote Desktop Users' (MS only)"
  win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
    - Administrators
    - Remote Desktop Users
    action: set

- name: "2.2.10 (L1) Ensure 'Back up files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeBackupPrivilege
    users:
    - Administrators
    action: set

- name: " 2.2.11 (L1) Ensure 'Change the system time' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeSystemTimePrivilege
    users:
    - Administrators
    - Local Service
    action: set

- name: "2.2.12 (L1) Ensure 'Change the time zone' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeTimeZonePrivilege
    users:
    - Administrators
    - Local Service
    action: set

- name: "2.2.13 (L1) Ensure 'Create a pagefile' is set to 'Administrators'"
  win_user_right:
    name: SeCreatePagefilePrivilege
    users:
    - Administrators
    action: set

- name: "2.2.14 (L1) Ensure 'Create a token object' is set to 'No One'"
  win_user_right:
    name: SeCreateTokenPrivilege
    users:
    action: set

- name: "2.2.15 (L1) Ensure 'Create global objects' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE'"
  win_user_right:
    name: SeCreateGlobalPrivilege
    users:
    - Administrators
    - Local Service
    - Network Service
    - Service
    action: set

- name: "2.2.16 (L1) Ensure 'Create permanent shared objects' is set to 'No One'"
  win_user_right:
    name: SeCreatePermanentPrivilege
    users:
    action: set

- name: "2.2.18 (L1) Ensure 'Create symbolic links' is set to 'Administrators, NT VIRTUAL MACHINE-Virtual Machines' (MS only)"
  win_user_right:
    name: SeCreateSymbolicLinkPrivilege
    users:
    - Administrators
    # can't find this account
    # - NT VIRTUAL MACHINE\Virtual Machines
    action: set

- name: "2.2.19 (L1) Ensure 'Debug programs' is set to 'Administrators'"
  win_user_right:
    name: SeDebugPrivilege
    users:
    - Administrators
    action: set

# This setting changes based on whether or not the machine is domain joined.
# For Domain joined nodes, use these users: Enterprise Admins group, 
# Domain Admins group, Local account.
# For All Systems, use the Guests group.
# TODO: Update 2.2.21 to execute according to domain/workgroup status.
- name: 2.2.21 (L1) Ensure 'Deny access to this computer from the network' is set to 'Guests, Local account and member of Administrators group' (MS only)
  win_user_right:
    name: SeDenyNetworkLogonRight
    users:
    - Guests
    #- Local Account
    action: set
  when: "'2.2.21' not in rules_list"

- name: "2.2.22 (L1) Ensure 'Deny log on as a batch job' to include 'Guests'"
  win_user_right:
    name: SeDenyBatchLogonRight
    users:
    - Guests
    action: set

- name: "2.2.23 (L1) Ensure 'Deny log on as a service' to include 'Guests'"
  win_user_right:
    name: SeDenyServiceLogonRight
    users:
    - Guests
    action: set

- name: "2.2.24 (L1) Ensure 'Deny log on locally' to include 'Guests'"
  win_user_right:
    name: SeDenyInteractiveLogonRight
    users:
    - Guests
    action: set

- name: "2.2.26 (L1) Ensure 'Deny log on through Remote Desktop Services' is set to 'Guests, Local account' (MS only)"
  win_user_right:
    name: SeDenyRemoteInteractiveLogonRight
    users:
    - Guests
    action: set 
  when: "'2.2.26' not in rules_list"

- name: "2.2.28 (L1) Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'No One'(MS only)"
  win_user_right:
    name: SeEnableDelegationPrivilege
    users: []
    action: set

- name: "2.2.29 (L1) Ensure 'Force shutdown from a remote system' is set to 'Administrators'"
  win_user_right:
    name: SeRemoteShutdownPrivilege
    users:
    - Administrators
    action: set
    
- name: "2.2.30 (L1) Ensure 'Generate security audits' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAuditPrivilege
    users:
    - LOCAL SERVICE
    - NETWORK SERVICE
    action: set

- name: "2.2.32 (L1) Ensure 'Impersonate a client after authentication' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' and (when the Web Server (IIS) Role with Web Services Role Service is installed) 'IIS_IUSRS' (MS only)"
  win_user_right:
    name: SeImpersonatePrivilege
    users:
    - Administrators
    - LOCAL SERVICE
    - NETWORK SERVICE
    - SERVICE
    action: set

- name: "2.2.33 (L1) Ensure 'Increase scheduling priority' is set to 'Administrators'"
  win_user_right:
    name: SeIncreaseBasePriorityPrivilege
    users:
    - Administrators
    action: set

- name: "2.2.34 (L1) Ensure 'Load and unload device drivers' is set to 'Administrators'"
  win_user_right:
    name: SeLoadDriverPrivilege
    users:
    - Administrators
    action: set
      
- name: "2.2.35 (L1) Ensure 'Lock pages in memory' is set to 'No One'"
  win_user_right:
    name: SeLockMemoryPrivilege
    users:
    action: set

- name: "2.2.38 (L1) Ensure 'Manage auditing and security log' is set to 'Administrators' (MS only)"
  win_user_right:
    name: SeSecurityPrivilege
    users:
    - Administrators
    action: set

- name: "2.2.39 (L1) Ensure 'Modify an object label' is set to 'No One'"
  win_user_right:
    name: SeReLabelPrivilege
    users:
    action: set

- name: "2.2.40 (L1) Ensure 'Modify firmware environment values' is set to 'Administrators'"
  win_user_right:
    name: SeSystemEnvironmentPrivilege
    users:
    - Administrators
    action: set

- name: "2.2.41 (L1) Ensure 'Perform volume maintenance tasks' is set to 'Administrators'"
  win_user_right:
    name: SeManageVolumePrivilege
    users:
    - Administrators
    action: set

- name: "2.2.42 (L1) Ensure 'Profile single process' is set to 'Administrators'"
  win_user_right:
    name: SeProfileSingleProcessPrivilege
    users:
    - Administrators
    action: set

- name: "2.2.43 (L1) Ensure 'Profile system performance' is set to 'Administrators, NT SERVICE-WdiServiceHost'"
  win_user_right:
    name: SeSystemProfilePrivilege
    users:
    - Administrators
    - NT SERVICE\WdiServiceHost
    action: set

- name: "2.2.44 (L1) Ensure 'Replace a process level token' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAssignPrimaryTokenPrivilege
    users:
    - LOCAL SERVICE
    - NETWORK SERVICE
    action: set

- name: "2.2.45 (L1) Ensure 'Restore files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeRestorePrivilege
    users:
    - Administrators
    action: set

- name: "2.2.46 (L1) Ensure 'Shut down the system' is set to 'Administrators'"
  win_user_right:
    name: SeShutdownPrivilege
    users:
    - Administrators
    action: set

- name: "2.2.48 (L1) Ensure 'Take ownership of files or other objects' is set to 'Administrators'"
  win_user_right:
    name: SeTakeOwnershipPrivilege
    users:
    - Administrators
    action: set
