---

# 1.2

# Fails during run but passed in assessor if not run
- name: 1.2.1 (L1) Ensure 'Account lockout duration' is set to '15 or more minute(s)'
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: 15
  tags:
    - never
    - 1.2.1

- name: 1.2.2 (L1) Ensure 'Account lockout threshold' is set to '10 or fewer invalid logon attempt(s), but not 0'
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: 5

- name: 1.2.3 (L1) Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: 15
