---

# 9.2 Private Profile

- name: "9.2.1 (L1) Ensure 'Windows Firewall: Private: Firewall state' is set to 'On (recommended)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: "EnableFirewall"
      data: "1"
      type: dword

- name: "9.2.2 (L1) Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: "DefaultInboundAction"
      data: "1"
      type: dword

- name: "9.2.3 (L1) Ensure 'Windows Firewall: Private: Outbound connections' is set to 'Allow (default)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: "DefaultOutboundAction"
      data: "0"
      type: dword

- name: "9.2.4 (L1) Ensure 'Windows Firewall: Private: Settings: Display a notification' is set to 'No'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: "DisableNotifications"
      data: "1"
      type: dword

- name: "9.2.5 (L1) Ensure 'Windows Firewall: Private: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\privatefw.log'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: "LogFilePath"
      data: "%systemroot%\\System32\\logfiles\\firewall\\privatefw.log"
      type: string

- name: "9.2.6 (L1) Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: "LogFileSize"
      data: "16384"
      type: dword

- name: "9.2.7 (L1) Ensure 'Windows Firewall: Private: Logging: Log dropped packets' is set to 'Yes'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: "LogDroppedPackets"
      data: "1"
      type: dword

- name: "9.2.8 (L1) Ensure 'Windows Firewall: Private: Logging: Log successful connections' is set to 'Yes'"
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: "LogSuccessfulConnections"
      data: "1"
      type: dword

