---

# 9.1 Domain Profile

- name: "9.1.1 (L1) Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: "EnableFirewall"
      data: "1"
      type: dword

- name: "9.1.2 (L1) Ensure 'Windows Firewall: Domain: Inbound connections' is set to 'Block (default)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: "DefaultInboundAction"
      data: "1"
      type: dword

- name: "9.1.3 (L1) Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: "DefaultOutboundAction"
      data: "0"
      type: dword

- name: "9.1.4 (L1) Ensure 'Windows Firewall: Domain: Settings: Display a notification' is set to 'No'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: "DisableNotifications"
      data: "1"
      type: dword

- name: "9.1.5 (L1) Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SYSTEMROOT%\\System32\\logfiles\\firewall\\domainfw.log'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: "LogFilePath"
      data: "%systemroot%\\System32\\logfiles\\firewall\\domainfw.log"
      type: string

- name: "9.1.6 (L1) Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: "LogFileSize"
      data: "16384"
      type: dword

- name: "9.1.7 (L1) Ensure 'Windows Firewall: Domain: Logging: Log dropped packets' is set to 'Yes'"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: "LogDroppedPackets"
      data: "1"
      type: dword

- name: "9.1.8 (L1) Ensure 'Windows Firewall: Domain: Logging: Log successful connections' is set to 'Yes'"
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: "LogSuccessfulConnections"
      data: "1"
      type: dword
