---

# section 5

- name: "5.7 (L1) Ensure 'Infrared monitor service (irmon)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\services\irmon
    name: "Start"
    data: "4"
    type: dword

- name: "5.8 (L1) Ensure 'Internet Connection Sharing (ICS) (SharedAccess)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess
    name: "Start"
    data: "4"
    type: dword

- name: "5.24 (L1) Ensure 'Remote Procedure Call (RPC) Locator (RpcLocator)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\RpcLocator
    name: "Start"
    data: "4"
    type: dword

- name: "5.30 (L1) Ensure 'SSDP Discovery (SSDPSRV)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\SSDPSRV
    name: "Start"
    data: "4"
    type: dword


- name: "5.31 (L1) Ensure 'UPnP Device Host (upnphost)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\upnphost
    name: "Start"
    data: "4"
    type: dword

- name: "5.35 (L1) Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\WMPNetworkSvc
    name: "Start"
    data: "4"
    type: dword

- name: "5.36 (L1) Ensure 'Windows Mobile Hotspot Service (icssvc)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\icssvc
    name: "Start"
    data: "4"
    type: dword

- name: "5.41 (L1) Ensure 'Xbox Accessory Management Service (XboxGipSvc)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc
    name: "Start"
    data: "4"
    type: dword

- name: "5.42 (L1) Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\XblAuthManager
    name: "Start"
    data: "4"
    type: dword

- name: "5.43 (L1) Ensure 'Xbox Live Game Save (XblGameSave)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\XblGameSave
    name: "Start"
    data: "4"
    type: dword

- name: "5.44 (L1) Ensure 'Xbox Live Networking Service (XboxNetApiSvc)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\XboxNetApiSvc
    name: "Start"
    data: "4"
    type: dword
