---

# 1.1

- name: 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)'
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24

- name: 1.1.2 (L1) Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: 60

- name: 1.1.3 (L1) Ensure 'Minimum password age' is set to '1 or more day(s)'
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: 1

- name: 1.1.4 (L1) Ensure 'Minimum password length' is set to '14 or more character(s)'
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: 14

# Rule is verified as applied but report shows 'Unknown'
- name: 1.1.5 (L1) Ensure 'Password must meet complexity requirements' is set to 'Enabled'
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1


# Rule is verified as applied but report shows 'Unknown'
- name: 1.1.6 (L1) Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
